language: perl
perl:
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
  - "5.008"
env:
  - ALIEN_FORCE=1
install:
  - cpanm --verbose --notest Alien::Base@0.023_01
script:
  - perl Build.PL && ./Build manifest && perl Build.PL && ./Build && ./Build test
  
