language: perl
perl:
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
  - "5.008"
env:
  - FORCE_ALIEN=1
  - NO_FORCE_ALIEN=1
install:
  - sudo cpanm --notest --skip-satisfied Alien::Base~0.023_01
sudo: required
